// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live-properties-server.proto

package com.namnh.serverliveproperties.grpc.proto;

public interface GetPropertyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetPropertyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .ServiceID serviceID = 1;</code>
   * @return Whether the serviceID field is set.
   */
  boolean hasServiceID();
  /**
   * <code>optional .ServiceID serviceID = 1;</code>
   * @return The serviceID.
   */
  com.namnh.serverliveproperties.grpc.proto.ServiceID getServiceID();
  /**
   * <code>optional .ServiceID serviceID = 1;</code>
   */
  com.namnh.serverliveproperties.grpc.proto.ServiceIDOrBuilder getServiceIDOrBuilder();

  /**
   * <code>optional string propertyName = 2;</code>
   * @return Whether the propertyName field is set.
   */
  boolean hasPropertyName();
  /**
   * <code>optional string propertyName = 2;</code>
   * @return The propertyName.
   */
  java.lang.String getPropertyName();
  /**
   * <code>optional string propertyName = 2;</code>
   * @return The bytes for propertyName.
   */
  com.google.protobuf.ByteString
      getPropertyNameBytes();
}
