// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live-properties-server.proto

package com.namnh.serverliveproperties.grpc.proto;

public final class LivePropertiesServerProto {
  private LivePropertiesServerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPropertyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPropertyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetPropertyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetPropertyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceID_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ServiceID_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Property_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Property_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034live-properties-server.proto\032\031google/p" +
      "rotobuf/any.proto\"r\n\022GetPropertyRequest\022" +
      "\"\n\tserviceID\030\001 \001(\0132\n.ServiceIDH\000\210\001\001\022\031\n\014p" +
      "ropertyName\030\002 \001(\tH\001\210\001\001B\014\n\n_serviceIDB\017\n\r" +
      "_propertyName\"\202\001\n\023GetPropertyResponse\022\022\n" +
      "\005error\030\001 \001(\021H\000\210\001\001\022\037\n\007payload\030\002 \001(\0132\t.Pro" +
      "pertyH\001\210\001\001\022\024\n\007message\030\003 \001(\tH\002\210\001\001B\010\n\006_err" +
      "orB\n\n\010_payloadB\n\n\010_message\"W\n\tServiceID\022" +
      "\030\n\013serviceName\030\001 \001(\tH\000\210\001\001\022\024\n\007address\030\002 \001" +
      "(\tH\001\210\001\001B\016\n\014_serviceNameB\n\n\010_address\"r\n\010P" +
      "roperty\022\017\n\002id\030\001 \001(\rH\000\210\001\001\022\021\n\004name\030\002 \001(\tH\001" +
      "\210\001\001\022(\n\005value\030\003 \001(\0132\024.google.protobuf.Any" +
      "H\002\210\001\001B\005\n\003_idB\007\n\005_nameB\010\n\006_value2P\n\024LiveP" +
      "ropertiesServer\0228\n\013getProperty\022\023.GetProp" +
      "ertyRequest\032\024.GetPropertyResponseBH\n)com" +
      ".namnh.serverliveproperties.grpc.protoB\031" +
      "LivePropertiesServerProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_GetPropertyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GetPropertyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPropertyRequest_descriptor,
        new java.lang.String[] { "ServiceID", "PropertyName", "ServiceID", "PropertyName", });
    internal_static_GetPropertyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetPropertyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetPropertyResponse_descriptor,
        new java.lang.String[] { "Error", "Payload", "Message", "Error", "Payload", "Message", });
    internal_static_ServiceID_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ServiceID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ServiceID_descriptor,
        new java.lang.String[] { "ServiceName", "Address", "ServiceName", "Address", });
    internal_static_Property_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Property_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Property_descriptor,
        new java.lang.String[] { "Id", "Name", "Value", "Id", "Name", "Value", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
