// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: live-properties-server.proto

package com.namnh.serverliveproperties.grpc.proto;

public interface ServiceIDOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ServiceID)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string serviceName = 1;</code>
   * @return Whether the serviceName field is set.
   */
  boolean hasServiceName();
  /**
   * <code>optional string serviceName = 1;</code>
   * @return The serviceName.
   */
  java.lang.String getServiceName();
  /**
   * <code>optional string serviceName = 1;</code>
   * @return The bytes for serviceName.
   */
  com.google.protobuf.ByteString
      getServiceNameBytes();

  /**
   * <code>optional string address = 2;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>optional string address = 2;</code>
   * @return The address.
   */
  java.lang.String getAddress();
  /**
   * <code>optional string address = 2;</code>
   * @return The bytes for address.
   */
  com.google.protobuf.ByteString
      getAddressBytes();
}
